### ISSUE TITLE
Does summarization.py work?

### ISSUE THREAD

**Issue by Coolnesss** [MaximumEntropy/Seq2Seq-PyTorch#9]
Hey, thanks for your implementations.

Trying to get the summarization code running, but I have a feeling it doesn't actually work (yet). Am i correct to assume so? For example, it's calling `read_nmt_data`  instead of  `read_summarization_data` and you've removed the file in your `refactor` branch.

Any tips on getting it to run?

**Comment by MaximumEntropy** [comment]
Hi

I'd recommend switching the refactor branch. It has length masking for the input sequences which is pretty important. There are still a couple of rough edges in the refactor branch though that I haven't found the time to fix (for example the BLEU computation always happens on the training set). 

However, if you want to stick to the master branch that should be fine as well. You can use nmt.py as is by just changing the src and trg paths for summarization. This will result in a separate word embedding layer for source and target as well as separate vocabularies.

**Comment by Coolnesss** [comment]
Hey @MaximumEntropy, thanks for your reply.

Trying to run on the `refactor` branch, I get 

```
Traceback (most recent call last):
  File "seq2seq.py", line 215, in <module>
    minibatch['src_lens']
  File "/home/chang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chang/yle/Seq2Seq-PyTorch/model.py", line 281, in forward
    trg_emb, (decoder_init_state, c_t), ctx
  File "/home/chang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chang/yle/Seq2Seq-PyTorch/layers.py", line 44, in forward
    output, (h_1_i, c_1_i), att = rnn(input, (h_0, c_0), ctx)
  File "/home/chang/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chang/yle/Seq2Seq-PyTorch/layers.py", line 195, in forward
    output.append(isinstance(hidden, tuple) and hidden[0] or hidden)
  File "/home/chang/.local/lib/python3.5/site-packages/torch/autograd/variable.py", line 123, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous

```

Any ideas? Here's my `config.json`

```
{
    "training": {
      "optimizer": "adam",
      "clip_c": 1,
      "lrate": 0.0001
    },
    "management": {
      "monitor_loss": 1000,
      "print_samples": 20000,
      "checkpoint_freq": 800000   
    },
    "data": {
      "src": "/home/chang/yle/Seq2Seq-PyTorch/src.txt",
      "trg": "/home/chang/yle/Seq2Seq-PyTorch/trg.txt",
      "valid_src": "/home/chang/yle/Seq2Seq-PyTorch/src_val.txt",
      "valid_trg": "/home/chang/yle/Seq2Seq-PyTorch/trg_val.txt",
      "test_src": "/home/chang/yle/Seq2Seq-PyTorch/src_val.txt",
      "test_trg": "/home/chang/yle/Seq2Seq-PyTorch/trg_val.txt",  
      "batch_size": 8,
      "n_words_trg": 30000,
      "valid_batch_size": 8,
      "n_words_src": 30000,
      "max_src_length": 3000,
      "max_trg_length": 500,
      "task": "summary",
      "save_dir": "/home/chang/yle/Seq2Seq-PyTorch/",
      "load_dir": false
    },
    "model": {
      "dim": 1000,
      "dim_trg": 1000,
      "use_dropout": false,
      "dim_word_src": 500,
      "n_words_src": 30000,
      "n_words": 30000,
      "dim_word_trg": 500,
      "n_layers_src": 1,
      "n_layers_trg": 1,
      "bidirectional": true,
      "decode": "greedy",
      "seq2seq": "attention",
      "optimizer": "adam"
    }
  }
  
  ```

The data is in parallel text format.

**Comment by tomahawklin** [comment]
Got same error here

**Comment by chenyangh** [comment]
@Coolnesss @tomahawklin 
The error is caused by 
`output.append(isinstance(hidden, tuple) and hidden[0] or hidden)`
which I think I know the idea, but the syntax does not make sense to me.
So I change it to 
```
if isinstance(hidden, tuple):
     output.append(hidden[0])
else:
     output.append(hidden)
```
or you can use
`output.append(hidden[0] if isinstance(hidden, tuple) else hidden)`
